# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{mir_extensions}
  s.version = "0.3.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Corey Ehmke", "Rod Monje"]
  s.date = %q{2010-08-01}
  s.description = %q{Standard extensions and utility methods for SEO Logic's Rails 3 apps.}
  s.email = %q{corey@seologic.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README",
     "README.rdoc"
  ]
  s.files = [
    ".bundle/config",
     ".document",
     ".gitignore",
     ".rspec",
     "Gemfile",
     "Gemfile.lock",
     "LICENSE",
     "README",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "app/controllers/application_controller.rb",
     "app/helpers/application_helper.rb",
     "app/models/primary.rb",
     "app/models/secondary.rb",
     "app/views/layouts/application.html.erb",
     "autotest/discover.rb",
     "config.ru",
     "config/application.rb",
     "config/boot.rb",
     "config/database.yml",
     "config/environment.rb",
     "config/environments/development.rb",
     "config/environments/production.rb",
     "config/environments/test.rb",
     "config/initializers/backtrace_silencers.rb",
     "config/initializers/inflections.rb",
     "config/initializers/mime_types.rb",
     "config/initializers/secret_token.rb",
     "config/initializers/session_store.rb",
     "config/locales/en.yml",
     "config/routes.rb",
     "db/development.sqlite3",
     "db/mir_ext_development.sqlite3",
     "db/mir_ext_test.sqlite3",
     "db/schema.rb",
     "db/seeds.rb",
     "db/test.sqlite3",
     "doc/README_FOR_APP",
     "lib/mir_extensions.rb",
     "lib/tasks/.gitkeep",
     "log/development.log",
     "log/production.log",
     "log/server.log",
     "log/test.log",
     "mir_extensions.gemspec",
     "public/404.html",
     "public/422.html",
     "public/500.html",
     "public/favicon.ico",
     "public/images/rails.png",
     "public/javascripts/application.js",
     "public/javascripts/controls.js",
     "public/javascripts/dragdrop.js",
     "public/javascripts/effects.js",
     "public/javascripts/prototype.js",
     "public/javascripts/rails.js",
     "public/robots.txt",
     "public/stylesheets/.gitkeep",
     "script/rails",
     "spec/controllers/application_controller_spec.rb",
     "spec/helpers/application_helper_spec.rb",
     "spec/mir_extensions_spec.rb",
     "spec/spec_helper.rb",
     "vendor/plugins/.gitkeep"
  ]
  s.homepage = %q{http://github.com/Bantik/mir_extensions}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Standard extensions and utility methods for SEO Logic's Rails 3 apps.}
  s.test_files = [
    "spec/controllers/application_controller_spec.rb",
     "spec/controllers/foos_controller_spec.rb",
     "spec/helpers/application_helper_spec.rb",
     "spec/mir_extensions_spec.rb",
     "spec/routing/foos_routing_spec.rb",
     "spec/spec_helper.rb",
     "spec/support/integration_example_group.rb",
     "spec/views/foos/edit.html.erb_spec.rb",
     "spec/views/foos/index.html.erb_spec.rb",
     "spec/views/foos/new.html.erb_spec.rb",
     "spec/views/foos/show.html.erb_spec.rb",
     "test/integration/foo_test.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 1.2.9"])
      s.add_development_dependency(%q<friendly_id>, [">= 0"])
    else
      s.add_dependency(%q<rspec>, [">= 1.2.9"])
      s.add_dependency(%q<friendly_id>, [">= 0"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 1.2.9"])
    s.add_dependency(%q<friendly_id>, [">= 0"])
  end
end

